apiVersion: v1
kind: ServiceAccount
metadata:
  name: healing-guard
  namespace: healing-guard
  labels:
    app.kubernetes.io/name: healing-guard
    app.kubernetes.io/instance: healing-guard
    app.kubernetes.io/component: serviceaccount
  annotations:
    # AWS IAM role for service account (IRSA)
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/healing-guard-role
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: healing-guard-role
  labels:
    app.kubernetes.io/name: healing-guard
    app.kubernetes.io/instance: healing-guard
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: healing-guard-binding
  labels:
    app.kubernetes.io/name: healing-guard
    app.kubernetes.io/instance: healing-guard
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: healing-guard
  namespace: healing-guard
roleRef:
  kind: ClusterRole
  name: healing-guard-role
  apiGroup: rbac.authorization.k8s.io